# Site settings
title: Tássio Virgínio
description: 'A soteropolitan lost in the world'
url: 'http://tassiovirginio.com'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'tassiovirginio'

author:
  name: 'Tássio Virgínio'
  email: contato@tassiovirginio.com
  twitter_username: tassiovirginio
  # facebook_username: tassiovirginio
  github_username:  tassiovirginio
  linkedin_username:  tassiovirginio
  lattes_id:  0517470966104640

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
